"""Control-plane registry (BA1): projects and their data sources.

The non-build-scoped face over `tables.projects` / `tables.sources` — plain
functions over an ``AsyncConnection`` (mirroring ``core.builds.lifecycle``),
NOT the build-scoped repo (which rejects these tables). Consumed by the
Console API routers (BA1b); the ingest/build triggers and idempotency store
land in BA1b/BA2.
"""

from core.registry.jobs import (
    Job,
    JobConflictError,
    JobNotFoundError,
    capture_config_snapshot,
    count_active_jobs,
    create_job,
    create_job_exclusive,
    find_reapable_jobs,
    find_unenqueued_jobs,
    get_eval_inputs_fingerprint,
    get_job,
    get_job_at,
    holds_lease,
    is_active_status,
    is_cancel_requested,
    lock_job,
    request_cancel,
    set_eval_inputs_fingerprint,
    set_progress,
)
from core.registry.store import (
    MANAGED_FILES_KEY,
    Project,
    ProjectExistsError,
    ProjectHasActiveJobsError,
    ProjectHasBuildsError,
    ProjectNotFoundError,
    Source,
    SourceNotFoundError,
    add_source,
    create_project,
    delete_project,
    get_project,
    list_projects,
    list_sources,
    update_project,
    update_source,
    upsert_managed_source,
)

__all__ = [
    "MANAGED_FILES_KEY",
    "Job",
    "JobConflictError",
    "JobNotFoundError",
    "Project",
    "ProjectExistsError",
    "ProjectHasActiveJobsError",
    "ProjectHasBuildsError",
    "ProjectNotFoundError",
    "Source",
    "SourceNotFoundError",
    "add_source",
    "capture_config_snapshot",
    "count_active_jobs",
    "create_job",
    "create_job_exclusive",
    "create_project",
    "delete_project",
    "find_reapable_jobs",
    "find_unenqueued_jobs",
    "get_eval_inputs_fingerprint",
    "get_job",
    "get_job_at",
    "get_project",
    "holds_lease",
    "is_active_status",
    "is_cancel_requested",
    "list_projects",
    "list_sources",
    "lock_job",
    "request_cancel",
    "set_eval_inputs_fingerprint",
    "set_progress",
    "update_project",
    "update_source",
    "upsert_managed_source",
]
