/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/projects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List projects */
    get: operations["listProjects"];
    put?: never;
    /** Create a project */
    post: operations["createProject"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{project}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    /** Get a project */
    get: operations["getProject"];
    put?: never;
    post?: never;
    /** Delete a project */
    delete: operations["deleteProject"];
    options?: never;
    head?: never;
    /** Update a project */
    patch: operations["updateProject"];
    trace?: never;
  };
  "/projects/{project}/sources": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    /** List data sources */
    get: operations["listSources"];
    put?: never;
    /** Register a data source */
    post: operations["addSource"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{project}/ingest": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Trigger ingestion (long operation) */
    post: operations["triggerIngest"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{project}/uploads": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Upload document file(s) into the project's managed corpus (v1.2, DR-010)
     * @description Multipart upload of one or more files into a server-managed corpus
     *     directory, registering/updating ONE canonical `file://` source (BA9
     *     uri-normalization stays server-owned). Client filenames are never used as
     *     paths — each file is sanitized to a generated name, the original kept as
     *     metadata. Optional per-file document metadata (`context`/`governance`
     *     only — `system` is stamped server-side, DR-010 rule 1) may accompany the
     *     upload, keyed by the submitted filename (which MUST be unique within a
     *     request — a duplicate submitted filename is refused with `400`, keeping the
     *     metadata key unambiguous). Files are accepted or rejected individually — a
     *     rejected extension or oversized single file is a STATED per-file refusal
     *     (with a reason), never a silent drop. The whole request is refused with
     *     `415` when the body is not `multipart/form-data` and `413` when its total
     *     size exceeds the configured limit.
     */
    post: operations["uploadDocuments"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{project}/build": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Trigger a full build (long operation) */
    post: operations["triggerBuild"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{project}/builds": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    /** List builds */
    get: operations["listBuilds"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{project}/builds/{build_id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
        build_id: components["parameters"]["BuildIdPath"];
      };
      cookie?: never;
    };
    /** Get a build */
    get: operations["getBuild"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{project}/builds/{build_id}/activate": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
        build_id: components["parameters"]["BuildIdPath"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Activate a ready build (atomic single-transaction switch, DR-001)
     * @description Preflight (DESIGN §14): build is `ready`, eval passes the threshold, and the
     *     three stores agree on build_id counts. Any failure rejects the activation
     *     (`409 BUILD_NOT_READY`).
     */
    post: operations["activateBuild"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{project}/builds/{build_id}/rollback": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
        build_id: components["parameters"]["BuildIdPath"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Roll back to a previous ready/archived build (atomic, DR-001) */
    post: operations["rollbackBuild"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{project}/builds/{build_id}/eval": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
        build_id: components["parameters"]["BuildIdPath"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Run the project's golden set against a build (async job, DESIGN §20/§27.5, v1.2)
     * @description Runs the project's configured golden set against the NAMED build — the
     *     same core eval path the CLI walks — landing the result where activation
     *     preflight reads §14 scores, so Console gating works with zero new
     *     coupling. Async (a golden set is unbounded work): returns `202` + a job
     *     envelope, watchable via `GET /jobs/{job_id}/events`. No request body: the
     *     build is named in the path and the golden set is the project's configured
     *     one. Idempotent per (build, golden-set fingerprint) — a duplicate run over
     *     the same build and golden set replays via the Idempotency-Key rather than
     *     recomputing.
     */
    post: operations["runBuildEval"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/jobs/{job_id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: components["parameters"]["JobIdPath"];
      };
      cookie?: never;
    };
    /** Get job status */
    get: operations["getJob"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/jobs/{job_id}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: components["parameters"]["JobIdPath"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Request job cancellation */
    post: operations["cancelJob"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/jobs/{job_id}/events": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: components["parameters"]["JobIdPath"];
      };
      cookie?: never;
    };
    /**
     * Job progress stream (Server-Sent Events)
     * @description SSE stream (DESIGN §27.2). Frozen event names: `job.update`, `job.done`,
     *     `job.failed`; each event's `data:` line is a JSON `JobEvent`. Example frames:
     *
     *         event: job.update
     *         data: {"job_id":"0c9f…","status":"running","step":"graph","progress":0.42,"message":null,"ts":"2026-07-02T07:12:03Z"}
     *
     *         event: job.done
     *         data: {"job_id":"0c9f…","status":"done","step":null,"progress":1,"message":"build ready","ts":"2026-07-02T07:15:40Z"}
     */
    get: operations["streamJobEvents"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{project}/documents": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    /** List documents (active build) */
    get: operations["listDocuments"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{project}/documents/{document_id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
        document_id: components["parameters"]["DocumentIdPath"];
      };
      cookie?: never;
    };
    /** Get a document (includes raw text) */
    get: operations["getDocument"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{project}/chunks": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    /** List chunks (active build) */
    get: operations["listChunks"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{project}/chunks/{chunk_id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
        chunk_id: components["parameters"]["ChunkIdPath"];
      };
      cookie?: never;
    };
    /** Get a chunk */
    get: operations["getChunk"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{project}/clean/preview": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Preview chunking (§10.2 抽樣預覽) — a pure function; nothing is persisted
     * @description Chunk ONE source with the given parameters and return the chunks that a build
     *     WOULD produce, without writing anything. The source is exactly one of
     *     `document_id` (that document's raw text, read from the ACTIVE build) or `text`
     *     (chunk the given text — usable before any build exists). Omitted `max_chars` /
     *     `overlap` fall back to the project's configured chunking values, then to the
     *     engine defaults, so the no-parameter preview shows what a build would actually do.
     *     The pair must satisfy `0 <= overlap < max_chars` — a relation two independent
     *     numeric bounds cannot express in JSON Schema, so it is enforced at runtime
     *     (violations answer 400 VALIDATION_ERROR).
     */
    post: operations["previewClean"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{project}/entities": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    /** List entities (active build) */
    get: operations["listEntities"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{project}/entities/{entity_id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
        entity_id: components["parameters"]["EntityIdPath"];
      };
      cookie?: never;
    };
    /** Get an entity */
    get: operations["getEntity"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{project}/relations": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    /** List relations (active build) */
    get: operations["listRelations"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{project}/relations/{relation_id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
        relation_id: components["parameters"]["RelationIdPath"];
      };
      cookie?: never;
    };
    /** Get a relation (with evidence) */
    get: operations["getRelation"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{project}/graph/subgraph": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    /** Neighborhood subgraph around an entity (active build) */
    get: operations["getSubgraph"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{project}/merge-candidates": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    /** List entity-resolution merge candidates */
    get: operations["listMergeCandidates"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{project}/merge-candidates/{candidate_id}/approve": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
        candidate_id: components["parameters"]["CandidateIdPath"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Approve a merge (recorded in review_ledger, DR-003) */
    post: operations["approveMergeCandidate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{project}/merge-candidates/{candidate_id}/reject": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
        candidate_id: components["parameters"]["CandidateIdPath"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reject a merge (recorded in review_ledger, DR-003) */
    post: operations["rejectMergeCandidate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{project}/merge-candidates/{candidate_id}/defer": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
        candidate_id: components["parameters"]["CandidateIdPath"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Defer a merge decision (stays in the review queue) */
    post: operations["deferMergeCandidate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{project}/query/semantic": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Semantic (vector) retrieval */
    post: operations["querySemantic"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{project}/query/graph": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Graph retrieval (multi-hop / paths, guardrailed — DESIGN §21/§27.6) */
    post: operations["queryGraph"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{project}/query/sql": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** NL→SQL retrieval (read-only role + sqlglot AST validation — DESIGN §21/§27.6) */
    post: operations["querySql"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{project}/query/global": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Global summary retrieval (community reports) */
    post: operations["queryGlobal"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{project}/query/hybrid": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Hybrid retrieval (router; default entry point)
     * @description Router selects and fuses modes; the routing trace is exposed in
     *     `data.debug.routing_decision` when `query_policy.expose_debug` allows it.
     *     Store outages degrade to the available modes with a typed warning instead of
     *     failing the whole query (DESIGN §22).
     */
    post: operations["queryHybrid"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{project}/health": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    /** Project health (status light + counts + drift, DESIGN §19) */
    get: operations["getHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{project}/metrics": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    /** Project metrics snapshot */
    get: operations["getMetrics"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{project}/eval": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    /** Latest eval report (golden-set metrics, DESIGN §20/§27.5) */
    get: operations["getEval"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description Success-envelope metadata (DESIGN §15). */
    Meta: {
      /** Format: uuid */
      request_id: string;
      /**
       * Format: uuid
       * @description Build that served the request; null when no build was involved.
       */
      build_id: string | null;
      elapsed_ms: number;
    };
    /**
     * @description Envelope metadata for paginated lists — next_cursor is required so clients can
     *     always distinguish the last page (null) from a non-conforming response.
     */
    PageMeta: {
      /** Format: uuid */
      request_id: string;
      /**
       * Format: uuid
       * @description Build that served the request; null when no build was involved.
       */
      build_id: string | null;
      elapsed_ms: number;
      /** @description Opaque cursor for the next page; null on the last page. */
      next_cursor: string | null;
    };
    /**
     * @description Frozen error-code enum (DESIGN §27.2; additive-only).
     * @enum {string}
     */
    ErrorCode:
      | "PROJECT_NOT_FOUND"
      | "BUILD_NOT_FOUND"
      | "BUILD_NOT_READY"
      | "NO_ACTIVE_BUILD"
      | "VALIDATION_ERROR"
      | "JOB_NOT_FOUND"
      | "JOB_CONFLICT"
      | "IDEMPOTENCY_CONFLICT"
      | "QUERY_UNSAFE"
      | "QUERY_TIMEOUT"
      | "STORE_UNAVAILABLE"
      | "RATE_LIMITED"
      | "INTERNAL";
    /**
     * @description The full frozen shape is always present — details is null rather than absent,
     *     so error consumers never branch on missing fields.
     */
    Error: {
      code: components["schemas"]["ErrorCode"];
      message: string;
      /** @description Machine-readable context (field errors, guardrail verdicts, …). */
      details: {
        [key: string]: unknown;
      } | null;
      /** Format: uuid */
      request_id: string;
    };
    ErrorResponse: {
      error: components["schemas"]["Error"];
    };
    /**
     * @description Frozen warning-code enum (DESIGN §27.2; additive-only).
     * @enum {string}
     */
    WarningCode:
      | "STORE_UNAVAILABLE"
      | "MODE_SKIPPED"
      | "PARTIAL_RESULTS"
      | "LOW_CONFIDENCE"
      | "GUARDRAIL_BLOCKED"
      | "TRUNCATED";
    Warning: {
      code: components["schemas"]["WarningCode"];
      message: string;
    };
    Project: {
      /** @description Stable project key (used in paths and store scoping). */
      name: string;
      display_name?: string | null;
      description?: string | null;
      config?: {
        [key: string]: unknown;
      };
      /** Format: date-time */
      created_at: string;
    };
    ProjectCreate: {
      name: string;
      display_name?: string | null;
      description?: string | null;
      config?: {
        [key: string]: unknown;
      };
    };
    ProjectUpdate: {
      display_name?: string | null;
      description?: string | null;
      config?: {
        [key: string]: unknown;
      };
    };
    Source: {
      /** Format: uuid */
      id: string;
      /** @description Connector kind (e.g. file, directory, url, database). */
      kind?: string;
      uri: string;
      metadata?: {
        [key: string]: unknown;
      };
      /** Format: date-time */
      added_at?: string;
    };
    SourceCreate: {
      kind?: string;
      uri: string;
      metadata?: {
        [key: string]: unknown;
      };
    };
    IngestRequest: {
      /** @description Restrict ingestion to these sources; omit for all. */
      source_ids?: string[];
    };
    BuildRequest: {
      /** @description Free-form operator note recorded on the build. */
      reason?: string | null;
    };
    /**
     * @description System/connector-generated document context — stamped server-side and
     *     immutable to clients (DR-010 rule 1). Never accepted on upload.
     */
    DocumentMetadataSystem: {
      /** @description The connector that produced the document (e.g. upload, url, database). */
      connector?: string;
      original_filename?: string | null;
    } & {
      [key: string]: unknown;
    };
    /**
     * @description General document context supplied by the user or source system. The
     *     concrete fields are defined by each project's metadata schema
     *     (type/required/display/filterable, in projects.config — DR-010 rule 2);
     *     this envelope fixes only the stable shape, never a global field list, so
     *     it stays domain-agnostic.
     */
    DocumentMetadataContext: {
      /** @description Human display name for the document. */
      title?: string | null;
      /** @description Project-defined document type. */
      document_type?: string | null;
      /** @description Project-defined key/values, typed by the project metadata schema. */
      attributes?: {
        [key: string]: unknown;
      };
    };
    /**
     * @description Visibility / sensitivity / retention. MUST NOT be mixed into embedding
     *     text (DR-010 rule 3); exposure to agents is gated by the project-level
     *     exposure allowlist (projects.config, DR-010 rule 7), never by mere
     *     presence in this object.
     */
    DocumentMetadataGovernance: {
      /** @description e.g. internal / public / restricted (project-defined vocabulary). */
      visibility?: string | null;
      classification?: string | null;
    } & {
      [key: string]: unknown;
    };
    /**
     * @description Stable-core document metadata envelope (DR-010). `system` is server-owned,
     *     `context` is project-defined document context, `governance` controls
     *     exposure/retention. Document-level metadata is stored once (DR-010 rule 5);
     *     chunk-local context (page/section/speaker/time) is separate and not a copy
     *     of this envelope.
     */
    DocumentMetadataEnvelope: {
      /** @description Envelope version; server-stamped, not client-writable. */
      schema_version: string;
      system: components["schemas"]["DocumentMetadataSystem"];
      context: components["schemas"]["DocumentMetadataContext"];
      governance: components["schemas"]["DocumentMetadataGovernance"];
    };
    /**
     * @description Client-supplied document metadata on upload: `context` and `governance`
     *     ONLY. `system` and `schema_version` are stamped server-side and rejected
     *     here (additionalProperties:false — the system namespace is structurally
     *     not client-writable, DR-010 rule 1), so human input can never silently
     *     overwrite connector/system metadata (DR-010 rule 4).
     */
    DocumentMetadataInput: {
      context?: components["schemas"]["DocumentMetadataContext"];
      governance?: components["schemas"]["DocumentMetadataGovernance"];
    };
    /** @description An accepted file — registered into the managed source with a canonical uri. */
    UploadedFileAccepted: {
      /** @description Server-sanitized stored name (client filenames are never used as paths). */
      filename: string;
      /** @description The filename as submitted; kept as document metadata. */
      original_filename?: string | null;
      /** @enum {string} */
      status: "accepted";
      /** @description Canonical file:// uri the managed source points at (BA9 rules). */
      document_uri: string;
      reason?: never;
    };
    /**
     * @description A rejected file — a STATED refusal (never a silent drop, DR-010): `reason`
     *     is required and non-empty, so a client can always explain why a file was
     *     not stored.
     */
    UploadedFileRejected: {
      /** @description Echoes the submitted name of the rejected file. */
      filename: string;
      /** @description The filename as submitted. */
      original_filename?: string | null;
      /** @enum {string} */
      status: "rejected";
      /** @description Why the file was rejected (e.g. extension not allowlisted, single-file size limit). */
      reason: string;
      document_uri?: never;
    };
    /**
     * @description Per-file outcome — exactly one of accepted (carries the canonical uri, no
     *     reason) or rejected (carries a non-empty reason, no uri). Each concrete
     *     variant forbids the other's discriminating field (`reason: false` /
     *     `document_uri: false`), so a rejected file WITHOUT a reason — a silent drop
     *     — is structurally unrepresentable (DR-010; the CleanPreviewRequest oneOf
     *     pattern makes codegen exact).
     */
    UploadedFile:
      components["schemas"]["UploadedFileAccepted"] | components["schemas"]["UploadedFileRejected"];
    UploadResult: {
      /**
       * Format: uuid
       * @description The canonical managed source registered/updated; null when nothing was accepted.
       */
      source_id: string | null;
      files: components["schemas"]["UploadedFile"][];
    };
    /**
     * @description Build lifecycle (DESIGN §4/§14).
     * @enum {string}
     */
    BuildStatus: "building" | "ready" | "active" | "failed" | "archived";
    Build: {
      /** Format: uuid */
      id: string;
      project: string;
      status: components["schemas"]["BuildStatus"];
      config_hash?: string | null;
      source_hash?: string | null;
      /** Format: date-time */
      started_at?: string | null;
      /** Format: date-time */
      finished_at?: string | null;
      /** Format: date-time */
      activated_at?: string | null;
      metrics?: {
        [key: string]: unknown;
      } | null;
      eval?: {
        [key: string]: unknown;
      } | null;
    };
    /** @enum {string} */
    JobStatus: "queued" | "running" | "done" | "failed" | "cancelled";
    /** @description 202 payload for long operations (DESIGN §15). */
    JobAccepted: {
      /** Format: uuid */
      job_id: string;
      status: components["schemas"]["JobStatus"];
    };
    Job: {
      /** Format: uuid */
      job_id: string;
      status: components["schemas"]["JobStatus"];
      /** @description e.g. ingest, build, reproject. */
      kind?: string;
      project?: string | null;
      /**
       * Format: uuid
       * @description Building build this job writes to; null for jobs not bound to a build (DESIGN §27.7).
       */
      build_id?: string | null;
      step?: string | null;
      progress?: number;
      message?: string | null;
      error?: components["schemas"]["Error"] | null;
      /** Format: date-time */
      created_at?: string | null;
      /** Format: date-time */
      finished_at?: string | null;
    };
    /**
     * @description SSE `data:` payload; event names are job.update|job.done|job.failed (DESIGN
     *     §27.2). The full frozen shape is always present — step/message are null rather
     *     than absent, so SSE consumers never branch on missing fields.
     */
    JobEvent: {
      /** Format: uuid */
      job_id: string;
      status: components["schemas"]["JobStatus"];
      step: string | null;
      progress: number;
      message: string | null;
      /** Format: date-time */
      ts: string;
    };
    Document: {
      /** Format: uuid */
      id: string;
      project?: string;
      /** Format: uuid */
      build_id: string;
      source_uri: string;
      content_hash?: string;
      mime?: string | null;
      metadata?: {
        [key: string]: unknown;
      };
      status?: string;
      /** Format: date-time */
      ingested_at?: string | null;
      /** @description Raw text; returned on detail GET only. */
      raw?: string | null;
    };
    Chunk: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      document_id: string;
      /** Format: uuid */
      build_id: string;
      ordinal: number;
      text: string;
      token_count?: number | null;
      start_offset?: number | null;
      end_offset?: number | null;
      /** Format: uuid */
      vector_point_id?: string | null;
      metadata?: {
        [key: string]: unknown;
      };
      status?: string;
    };
    /** @description Chunk a document's raw text, read from the ACTIVE build. */
    CleanPreviewByDocument: {
      /** @description Window size; omitted → project config, then engine default. */
      max_chars?: number;
      /** @description Window overlap; omitted → project config, then engine default. */
      overlap?: number;
      /** Format: uuid */
      document_id: string;
      text?: never;
    };
    /** @description Chunk the given text directly — works before any build exists. */
    CleanPreviewByText: {
      /** @description Window size; omitted → project config, then engine default. */
      max_chars?: number;
      /** @description Window overlap; omitted → project config, then engine default. */
      overlap?: number;
      text: string;
      document_id?: never;
    };
    /**
     * @description Exactly ONE source: document_id or text. The two variants are concrete
     *     object schemas (each closed with additionalProperties: false), and each
     *     declares the OTHER source with the `false` schema — so codegen emits it
     *     as `?: never` and the union is EXACT, not merely structural: a payload
     *     naming both sources fails to type even when built in a variable (excess-
     *     property checks only cover literals). Both sources, or neither, is 400
     *     at the API either way.
     */
    CleanPreviewRequest:
      components["schemas"]["CleanPreviewByDocument"] | components["schemas"]["CleanPreviewByText"];
    /**
     * @description One previewed chunk. Computed on the fly and never stored, so it carries no
     *     id/document_id/build_id — offsets satisfy raw[start_offset:end_offset] == text
     *     exactly (the same invariant stored chunks freeze for §27.4 evidence spans).
     */
    CleanPreviewChunk: {
      ordinal: number;
      text: string;
      start_offset: number;
      /** @description Exclusive end, per Python slice semantics. */
      end_offset: number;
      token_count: number;
    };
    CleanPreviewResult: {
      chunks: components["schemas"]["CleanPreviewChunk"][];
    };
    CleanPreviewResponse: {
      data: components["schemas"]["CleanPreviewResult"];
      meta: components["schemas"]["Meta"];
    };
    /**
     * @description Entity/relation lifecycle (DESIGN §4/§17).
     * @enum {string}
     */
    LifecycleStatus: "active" | "deprecated" | "merged" | "rejected" | "needs_review";
    /** @enum {string} */
    ReviewStatus: "unreviewed" | "approved" | "rejected";
    /** @enum {string} */
    CreatedBy: "rule" | "llm" | "manual";
    Entity: {
      /**
       * Format: uuid
       * @description canonical_id shared by all three stores.
       */
      id: string;
      project?: string;
      /** Format: uuid */
      build_id: string;
      type: string;
      canonical_name: string;
      /** @description Cross-build stable fingerprint (DESIGN §27.3). */
      entity_key: string;
      attributes?: {
        [key: string]: unknown;
      };
      status: components["schemas"]["LifecycleStatus"];
      review_status?: components["schemas"]["ReviewStatus"];
      created_by?: components["schemas"]["CreatedBy"];
      /** Format: date-time */
      created_at?: string | null;
      /** Format: date-time */
      updated_at?: string | null;
    };
    RelationEvidence: {
      /** Format: uuid */
      id: string;
      /** @enum {string} */
      evidence_type: "chunk" | "row" | "manual";
      evidence_ref?: string | null;
      /** Format: uuid */
      chunk_id?: string | null;
      start_offset?: number | null;
      end_offset?: number | null;
      quote?: string | null;
      /** @description Denormalized so evidence survives pruning of old chunks (DESIGN §27.4). */
      source_uri?: string | null;
      confidence?: number | null;
    };
    Relation: {
      /** Format: uuid */
      id: string;
      project?: string;
      /** Format: uuid */
      build_id: string;
      /** Format: uuid */
      src_entity_id: string;
      /** Format: uuid */
      dst_entity_id: string;
      type: string;
      attributes?: {
        [key: string]: unknown;
      };
      /** @description Cross-build stable fingerprint (DESIGN §27.3). */
      relation_signature?: string;
      status: components["schemas"]["LifecycleStatus"];
      review_status?: components["schemas"]["ReviewStatus"];
      created_by?: components["schemas"]["CreatedBy"];
      confidence?: number | null;
      evidence?: components["schemas"]["RelationEvidence"][];
      /** Format: date-time */
      created_at?: string | null;
      /** Format: date-time */
      updated_at?: string | null;
    };
    /** @enum {string} */
    MergeCandidateStatus: "pending" | "approved" | "rejected" | "deferred";
    MergeCandidate: {
      /** Format: uuid */
      id: string;
      project?: string;
      /** Format: uuid */
      build_id: string;
      /** Format: uuid */
      left_entity_id: string;
      /** Format: uuid */
      right_entity_id: string;
      score: number;
      features?: {
        [key: string]: unknown;
      };
      status: components["schemas"]["MergeCandidateStatus"];
      /** @enum {string|null} */
      decision?: "approve" | "reject" | "defer" | null;
      decided_by?: string | null;
      /** Format: date-time */
      decided_at?: string | null;
      reason?: string | null;
      /** @description Blast-radius info used to rank the review queue. */
      impact?: {
        [key: string]: unknown;
      } | null;
      left_snapshot?: {
        [key: string]: unknown;
      } | null;
      right_snapshot?: {
        [key: string]: unknown;
      } | null;
    };
    ReviewDecisionRequest: {
      reason?: string | null;
    };
    GraphNode: {
      /** Format: uuid */
      id: string;
      type?: string | null;
      label?: string | null;
      properties?: {
        [key: string]: unknown;
      };
    };
    GraphEdge: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      src: string;
      /** Format: uuid */
      dst: string;
      type: string;
      confidence?: number | null;
      properties?: {
        [key: string]: unknown;
      };
    };
    GraphPath: {
      nodes: string[];
      edges: string[];
    };
    GraphContext: {
      nodes: components["schemas"]["GraphNode"][];
      edges: components["schemas"]["GraphEdge"][];
      paths?: components["schemas"]["GraphPath"][];
    };
    /** @enum {string} */
    QueryMode: "semantic" | "graph" | "sql" | "global" | "hybrid";
    QueryRequest: {
      /** @description Natural-language question. */
      query: string;
      /** @description Capped by `query_policy.max_top_k`. */
      top_k?: number | null;
      /** @description Store-level filters (e.g. entity type, document metadata). */
      filters?: {
        [key: string]: unknown;
      };
      /** @description Mode-specific options (e.g. graph: max_hops; capped by query_policy). */
      options?: {
        [key: string]: unknown;
      };
    };
    /** @enum {string} */
    SourceRefType: "document" | "chunk" | "entity" | "relation" | "row";
    SourceRef: {
      source_type: components["schemas"]["SourceRefType"];
      id: string;
      source_uri?: string | null;
      metadata?: {
        [key: string]: unknown;
      };
    };
    /** @enum {string} */
    ResultType: "chunk" | "entity" | "relation" | "path" | "row" | "community_report";
    /**
     * @description One retrieval hit. `source_refs` is mandatory and non-empty (`require_sources`,
     *     DESIGN §16/§27.2) — every answer must be traceable to sources. Results are
     *     ordered score desc, ties broken by id.
     */
    RetrievalResult: {
      result_type: components["schemas"]["ResultType"];
      id: string;
      title?: string | null;
      text?: string | null;
      score: number;
      confidence?: number | null;
      source_refs: components["schemas"]["SourceRef"][];
    };
    /** @description Router trace (§16) — which modes ran and why. */
    RoutingDecision: {
      selected: components["schemas"]["QueryMode"][];
      skipped: components["schemas"]["QueryMode"][];
      reason?: string | null;
      confidence?: number | null;
    };
    /** @description Typed debug block (§16); evolution is additive. */
    QueryDebug: {
      stores_used: string[];
      retrieval_plan: string[];
      /** @description Null for single-mode queries that bypass the router. */
      routing_decision: components["schemas"]["RoutingDecision"] | null;
      latency_ms: number;
    };
    QueryResult: {
      mode: components["schemas"]["QueryMode"];
      /**
       * Format: uuid
       * @description Active build the query ran against (DR-001).
       */
      build_id: string;
      results: components["schemas"]["RetrievalResult"][];
      graph_context?: components["schemas"]["GraphContext"] | null;
      warnings: components["schemas"]["Warning"][];
      /**
       * @description Emitted only when `query_policy.expose_debug` and the caller's role allow
       *     it (§16/§21); null otherwise.
       */
      debug?: components["schemas"]["QueryDebug"] | null;
    };
    /**
     * @description Project status light (DESIGN §19).
     * @enum {string}
     */
    HealthStatus: "healthy" | "needs_review" | "build_failed" | "index_drift" | "eval_regression";
    HealthReport: {
      status: components["schemas"]["HealthStatus"];
      /** Format: uuid */
      active_build_id?: string | null;
      /** @description sources/documents/chunks/entities/relations counts. */
      counts?: {
        [key: string]: number;
      };
      pending_review?: number;
      /** @description Per-store build_id count reconciliation (PG vs Neo4j/Qdrant). */
      drift?: {
        [key: string]: unknown;
      } | null;
      warnings?: components["schemas"]["Warning"][];
    } & {
      [key: string]: unknown;
    };
    EvalReport: {
      /** Format: uuid */
      build_id?: string | null;
      passed?: boolean | null;
      regression?: boolean | null;
      /**
       * @description Includes GraphRAG metrics `path_validity`, `relation_hit_rate`,
       *     `groundedness` (DESIGN §27.5) plus recall/similarity/citation coverage.
       */
      metrics?: {
        [key: string]: number;
      };
    } & {
      [key: string]: unknown;
    };
    ProjectResponse: {
      data: components["schemas"]["Project"];
      meta: components["schemas"]["Meta"];
    };
    ProjectListResponse: {
      data: components["schemas"]["Project"][];
      meta: components["schemas"]["PageMeta"];
    };
    SourceResponse: {
      data: components["schemas"]["Source"];
      meta: components["schemas"]["Meta"];
    };
    SourceListResponse: {
      data: components["schemas"]["Source"][];
      meta: components["schemas"]["PageMeta"];
    };
    BuildResponse: {
      data: components["schemas"]["Build"];
      meta: components["schemas"]["Meta"];
    };
    BuildListResponse: {
      data: components["schemas"]["Build"][];
      meta: components["schemas"]["PageMeta"];
    };
    JobResponse: {
      data: components["schemas"]["Job"];
      meta: components["schemas"]["Meta"];
    };
    JobAcceptedResponse: {
      data: components["schemas"]["JobAccepted"];
      meta: components["schemas"]["Meta"];
    };
    UploadResponse: {
      data: components["schemas"]["UploadResult"];
      meta: components["schemas"]["Meta"];
    };
    DocumentResponse: {
      data: components["schemas"]["Document"];
      meta: components["schemas"]["Meta"];
    };
    DocumentListResponse: {
      data: components["schemas"]["Document"][];
      meta: components["schemas"]["PageMeta"];
    };
    ChunkResponse: {
      data: components["schemas"]["Chunk"];
      meta: components["schemas"]["Meta"];
    };
    ChunkListResponse: {
      data: components["schemas"]["Chunk"][];
      meta: components["schemas"]["PageMeta"];
    };
    EntityResponse: {
      data: components["schemas"]["Entity"];
      meta: components["schemas"]["Meta"];
    };
    EntityListResponse: {
      data: components["schemas"]["Entity"][];
      meta: components["schemas"]["PageMeta"];
    };
    RelationResponse: {
      data: components["schemas"]["Relation"];
      meta: components["schemas"]["Meta"];
    };
    RelationListResponse: {
      data: components["schemas"]["Relation"][];
      meta: components["schemas"]["PageMeta"];
    };
    MergeCandidateResponse: {
      data: components["schemas"]["MergeCandidate"];
      meta: components["schemas"]["Meta"];
    };
    MergeCandidateListResponse: {
      data: components["schemas"]["MergeCandidate"][];
      meta: components["schemas"]["PageMeta"];
    };
    SubgraphResponse: {
      data: components["schemas"]["GraphContext"];
      meta: components["schemas"]["Meta"];
    };
    QueryResponse: {
      data: components["schemas"]["QueryResult"];
      meta: components["schemas"]["Meta"];
    };
    HealthResponse: {
      data: components["schemas"]["HealthReport"];
      meta: components["schemas"]["Meta"];
    };
    MetricsResponse: {
      data: {
        [key: string]: unknown;
      };
      meta: components["schemas"]["Meta"];
    };
    EvalResponse: {
      data: components["schemas"]["EvalReport"];
      meta: components["schemas"]["Meta"];
    };
  };
  responses: {
    /**
     * @description Error envelope. Status → code mapping: 400 `VALIDATION_ERROR`/`QUERY_UNSAFE` ·
     *     404 `PROJECT_NOT_FOUND`/`BUILD_NOT_FOUND`/`JOB_NOT_FOUND` · 409
     *     `IDEMPOTENCY_CONFLICT`/`JOB_CONFLICT`/`BUILD_NOT_READY`/`NO_ACTIVE_BUILD` ·
     *     429 `RATE_LIMITED` · 503 `STORE_UNAVAILABLE` · 504 `QUERY_TIMEOUT` · 500 `INTERNAL`.
     *     The upload endpoint also returns 413 (total size over the limit) and 415
     *     (body not multipart/form-data); like a 405, these carry no dedicated code and
     *     surface as VALIDATION_ERROR through the coarse 4xx fallback.
     */
    Error: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "error": {
         *         "code": "PROJECT_NOT_FOUND",
         *         "message": "project 'acme' does not exist",
         *         "details": null,
         *         "request_id": "6f1c2a4e-9b0d-4c39-9a55-1f2f3a4b5c6d"
         *       }
         *     }
         */
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /**
     * @description Conflict — `IDEMPOTENCY_CONFLICT` (same Idempotency-Key, different request),
     *     `JOB_CONFLICT` (overlapping job), `BUILD_NOT_READY` (activation preflight
     *     failed) or `NO_ACTIVE_BUILD`.
     */
    Conflict: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
  };
  parameters: {
    ProjectPath: string;
    BuildIdPath: string;
    JobIdPath: string;
    DocumentIdPath: string;
    ChunkIdPath: string;
    EntityIdPath: string;
    RelationIdPath: string;
    CandidateIdPath: string;
    /** @description Page size (default 50 🔧). */
    Limit: number;
    /** @description Opaque cursor from `meta.next_cursor`; omit for the first page. */
    Cursor: string;
    /** @description `field:asc` or `field:desc`. */
    Sort: string;
    /** @description Field filters as `filter[field]=value` (deepObject style). */
    Filter: {
      [key: string]: string;
    };
    /**
     * @description Client-generated key (≤255 chars). Same key + same request hash replays the
     *     stored original response; same key + different request hash → `409
     *     IDEMPOTENCY_CONFLICT`. Keys expire after the configured TTL (default 24h 🔧).
     */
    IdempotencyKey: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listProjects: {
    parameters: {
      query?: {
        /** @description Page size (default 50 🔧). */
        limit?: components["parameters"]["Limit"];
        /** @description Opaque cursor from `meta.next_cursor`; omit for the first page. */
        cursor?: components["parameters"]["Cursor"];
        /** @description `field:asc` or `field:desc`. */
        sort?: components["parameters"]["Sort"];
        /** @description Field filters as `filter[field]=value` (deepObject style). */
        filter?: components["parameters"]["Filter"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Projects page. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectListResponse"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  createProject: {
    parameters: {
      query?: never;
      header?: {
        /**
         * @description Client-generated key (≤255 chars). Same key + same request hash replays the
         *     stored original response; same key + different request hash → `409
         *     IDEMPOTENCY_CONFLICT`. Keys expire after the configured TTL (default 24h 🔧).
         */
        "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectCreate"];
      };
    };
    responses: {
      /** @description Project created. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectResponse"];
        };
      };
      409: components["responses"]["Conflict"];
      default: components["responses"]["Error"];
    };
  };
  getProject: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Project. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "data": {
           *         "name": "acme",
           *         "display_name": "ACME corpus",
           *         "description": "Product & org knowledge base",
           *         "config": {},
           *         "created_at": "2026-07-01T09:00:00Z"
           *       },
           *       "meta": {
           *         "request_id": "6f1c2a4e-9b0d-4c39-9a55-1f2f3a4b5c6d",
           *         "build_id": null,
           *         "elapsed_ms": 4
           *       }
           *     }
           */
          "application/json": components["schemas"]["ProjectResponse"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  deleteProject: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted (no body). */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components["responses"]["Error"];
    };
  };
  updateProject: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectUpdate"];
      };
    };
    responses: {
      /** @description Updated project. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectResponse"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  listSources: {
    parameters: {
      query?: {
        /** @description Page size (default 50 🔧). */
        limit?: components["parameters"]["Limit"];
        /** @description Opaque cursor from `meta.next_cursor`; omit for the first page. */
        cursor?: components["parameters"]["Cursor"];
        /** @description `field:asc` or `field:desc`. */
        sort?: components["parameters"]["Sort"];
        /** @description Field filters as `filter[field]=value` (deepObject style). */
        filter?: components["parameters"]["Filter"];
      };
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Sources page. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SourceListResponse"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  addSource: {
    parameters: {
      query?: never;
      header?: {
        /**
         * @description Client-generated key (≤255 chars). Same key + same request hash replays the
         *     stored original response; same key + different request hash → `409
         *     IDEMPOTENCY_CONFLICT`. Keys expire after the configured TTL (default 24h 🔧).
         */
        "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
      };
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SourceCreate"];
      };
    };
    responses: {
      /** @description Source registered. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SourceResponse"];
        };
      };
      409: components["responses"]["Conflict"];
      default: components["responses"]["Error"];
    };
  };
  triggerIngest: {
    parameters: {
      query?: never;
      header?: {
        /**
         * @description Client-generated key (≤255 chars). Same key + same request hash replays the
         *     stored original response; same key + different request hash → `409
         *     IDEMPOTENCY_CONFLICT`. Keys expire after the configured TTL (default 24h 🔧).
         */
        "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
      };
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["IngestRequest"];
      };
    };
    responses: {
      /** @description Ingest job accepted. */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "data": {
           *         "job_id": "0c9f7a3e-2f65-4f0a-8a2b-7d1e9c4b5a6f",
           *         "status": "queued"
           *       },
           *       "meta": {
           *         "request_id": "3f0a1b2c-4d5e-6f70-8192-a3b4c5d6e7f8",
           *         "build_id": null,
           *         "elapsed_ms": 12
           *       }
           *     }
           */
          "application/json": components["schemas"]["JobAcceptedResponse"];
        };
      };
      409: components["responses"]["Conflict"];
      default: components["responses"]["Error"];
    };
  };
  uploadDocuments: {
    parameters: {
      query?: never;
      header?: {
        /**
         * @description Client-generated key (≤255 chars). Same key + same request hash replays the
         *     stored original response; same key + different request hash → `409
         *     IDEMPOTENCY_CONFLICT`. Keys expire after the configured TTL (default 24h 🔧).
         */
        "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
      };
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": {
          files: string[];
          /**
           * @description Optional document metadata keyed by each file's submitted
           *     filename → its DocumentMetadataInput (context/governance only;
           *     the system namespace is stamped server-side and rejected here).
           *     Submitted filenames MUST be unique within a request — the
           *     filename is both this metadata key and the managed-corpus
           *     identity — so a request containing duplicate submitted filenames
           *     is refused (400); the key is therefore never ambiguous.
           */
          metadata?: {
            [key: string]: components["schemas"]["DocumentMetadataInput"];
          };
        };
      };
    };
    responses: {
      /** @description Upload processed; per-file manifest + the managed source. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UploadResponse"];
        };
      };
      409: components["responses"]["Conflict"];
      413: components["responses"]["Error"];
      415: components["responses"]["Error"];
      default: components["responses"]["Error"];
    };
  };
  triggerBuild: {
    parameters: {
      query?: never;
      header?: {
        /**
         * @description Client-generated key (≤255 chars). Same key + same request hash replays the
         *     stored original response; same key + different request hash → `409
         *     IDEMPOTENCY_CONFLICT`. Keys expire after the configured TTL (default 24h 🔧).
         */
        "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
      };
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["BuildRequest"];
      };
    };
    responses: {
      /** @description Build job accepted. */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobAcceptedResponse"];
        };
      };
      409: components["responses"]["Conflict"];
      default: components["responses"]["Error"];
    };
  };
  listBuilds: {
    parameters: {
      query?: {
        /** @description Page size (default 50 🔧). */
        limit?: components["parameters"]["Limit"];
        /** @description Opaque cursor from `meta.next_cursor`; omit for the first page. */
        cursor?: components["parameters"]["Cursor"];
        /** @description `field:asc` or `field:desc`. */
        sort?: components["parameters"]["Sort"];
        /** @description Field filters as `filter[field]=value` (deepObject style). */
        filter?: components["parameters"]["Filter"];
      };
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Builds page. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BuildListResponse"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  getBuild: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
        build_id: components["parameters"]["BuildIdPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Build. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BuildResponse"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  activateBuild: {
    parameters: {
      query?: never;
      header?: {
        /**
         * @description Client-generated key (≤255 chars). Same key + same request hash replays the
         *     stored original response; same key + different request hash → `409
         *     IDEMPOTENCY_CONFLICT`. Keys expire after the configured TTL (default 24h 🔧).
         */
        "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
      };
      path: {
        project: components["parameters"]["ProjectPath"];
        build_id: components["parameters"]["BuildIdPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Build activated; previous active build archived. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BuildResponse"];
        };
      };
      409: components["responses"]["Conflict"];
      default: components["responses"]["Error"];
    };
  };
  rollbackBuild: {
    parameters: {
      query?: never;
      header?: {
        /**
         * @description Client-generated key (≤255 chars). Same key + same request hash replays the
         *     stored original response; same key + different request hash → `409
         *     IDEMPOTENCY_CONFLICT`. Keys expire after the configured TTL (default 24h 🔧).
         */
        "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
      };
      path: {
        project: components["parameters"]["ProjectPath"];
        build_id: components["parameters"]["BuildIdPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Rollback applied; the given build is active again. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BuildResponse"];
        };
      };
      409: components["responses"]["Conflict"];
      default: components["responses"]["Error"];
    };
  };
  runBuildEval: {
    parameters: {
      query?: never;
      header?: {
        /**
         * @description Client-generated key (≤255 chars). Same key + same request hash replays the
         *     stored original response; same key + different request hash → `409
         *     IDEMPOTENCY_CONFLICT`. Keys expire after the configured TTL (default 24h 🔧).
         */
        "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
      };
      path: {
        project: components["parameters"]["ProjectPath"];
        build_id: components["parameters"]["BuildIdPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Eval job accepted. */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobAcceptedResponse"];
        };
      };
      409: components["responses"]["Conflict"];
      default: components["responses"]["Error"];
    };
  };
  getJob: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: components["parameters"]["JobIdPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Job. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobResponse"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  cancelJob: {
    parameters: {
      query?: never;
      header?: {
        /**
         * @description Client-generated key (≤255 chars). Same key + same request hash replays the
         *     stored original response; same key + different request hash → `409
         *     IDEMPOTENCY_CONFLICT`. Keys expire after the configured TTL (default 24h 🔧).
         */
        "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
      };
      path: {
        job_id: components["parameters"]["JobIdPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Cancellation requested. */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobAcceptedResponse"];
        };
      };
      409: components["responses"]["Conflict"];
      default: components["responses"]["Error"];
    };
  };
  streamJobEvents: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: components["parameters"]["JobIdPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Event stream; ends after `job.done` / `job.failed`. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/event-stream": components["schemas"]["JobEvent"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  listDocuments: {
    parameters: {
      query?: {
        /** @description Page size (default 50 🔧). */
        limit?: components["parameters"]["Limit"];
        /** @description Opaque cursor from `meta.next_cursor`; omit for the first page. */
        cursor?: components["parameters"]["Cursor"];
        /** @description `field:asc` or `field:desc`. */
        sort?: components["parameters"]["Sort"];
        /** @description Field filters as `filter[field]=value` (deepObject style). */
        filter?: components["parameters"]["Filter"];
      };
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Documents page. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DocumentListResponse"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  getDocument: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
        document_id: components["parameters"]["DocumentIdPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Document. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DocumentResponse"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  listChunks: {
    parameters: {
      query?: {
        /** @description Page size (default 50 🔧). */
        limit?: components["parameters"]["Limit"];
        /** @description Opaque cursor from `meta.next_cursor`; omit for the first page. */
        cursor?: components["parameters"]["Cursor"];
        /** @description `field:asc` or `field:desc`. */
        sort?: components["parameters"]["Sort"];
        /** @description Field filters as `filter[field]=value` (deepObject style). */
        filter?: components["parameters"]["Filter"];
      };
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Chunks page. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChunkListResponse"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  getChunk: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
        chunk_id: components["parameters"]["ChunkIdPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Chunk. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChunkResponse"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  previewClean: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CleanPreviewRequest"];
      };
    };
    responses: {
      /**
       * @description The chunks these parameters would produce. meta.build_id names the active
       *     build the document was read from; null for the `text` source (no build
       *     involved).
       */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CleanPreviewResponse"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  listEntities: {
    parameters: {
      query?: {
        /** @description Page size (default 50 🔧). */
        limit?: components["parameters"]["Limit"];
        /** @description Opaque cursor from `meta.next_cursor`; omit for the first page. */
        cursor?: components["parameters"]["Cursor"];
        /** @description `field:asc` or `field:desc`. */
        sort?: components["parameters"]["Sort"];
        /** @description Field filters as `filter[field]=value` (deepObject style). */
        filter?: components["parameters"]["Filter"];
      };
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Entities page. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EntityListResponse"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  getEntity: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
        entity_id: components["parameters"]["EntityIdPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Entity. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EntityResponse"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  listRelations: {
    parameters: {
      query?: {
        /** @description Page size (default 50 🔧). */
        limit?: components["parameters"]["Limit"];
        /** @description Opaque cursor from `meta.next_cursor`; omit for the first page. */
        cursor?: components["parameters"]["Cursor"];
        /** @description `field:asc` or `field:desc`. */
        sort?: components["parameters"]["Sort"];
        /** @description Field filters as `filter[field]=value` (deepObject style). */
        filter?: components["parameters"]["Filter"];
      };
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Relations page. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RelationListResponse"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  getRelation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
        relation_id: components["parameters"]["RelationIdPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Relation. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RelationResponse"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  getSubgraph: {
    parameters: {
      query: {
        entity_id: string;
        /** @description Traversal depth; capped by `query_policy.max_graph_hops`. */
        hops?: number;
        /** @description Page size (default 50 🔧). */
        limit?: components["parameters"]["Limit"];
      };
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Subgraph. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SubgraphResponse"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  listMergeCandidates: {
    parameters: {
      query?: {
        /** @description Page size (default 50 🔧). */
        limit?: components["parameters"]["Limit"];
        /** @description Opaque cursor from `meta.next_cursor`; omit for the first page. */
        cursor?: components["parameters"]["Cursor"];
        /** @description `field:asc` or `field:desc`. */
        sort?: components["parameters"]["Sort"];
        /** @description Field filters as `filter[field]=value` (deepObject style). */
        filter?: components["parameters"]["Filter"];
      };
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Merge candidates page. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MergeCandidateListResponse"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  approveMergeCandidate: {
    parameters: {
      query?: never;
      header?: {
        /**
         * @description Client-generated key (≤255 chars). Same key + same request hash replays the
         *     stored original response; same key + different request hash → `409
         *     IDEMPOTENCY_CONFLICT`. Keys expire after the configured TTL (default 24h 🔧).
         */
        "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
      };
      path: {
        project: components["parameters"]["ProjectPath"];
        candidate_id: components["parameters"]["CandidateIdPath"];
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ReviewDecisionRequest"];
      };
    };
    responses: {
      /** @description Decision recorded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MergeCandidateResponse"];
        };
      };
      409: components["responses"]["Conflict"];
      default: components["responses"]["Error"];
    };
  };
  rejectMergeCandidate: {
    parameters: {
      query?: never;
      header?: {
        /**
         * @description Client-generated key (≤255 chars). Same key + same request hash replays the
         *     stored original response; same key + different request hash → `409
         *     IDEMPOTENCY_CONFLICT`. Keys expire after the configured TTL (default 24h 🔧).
         */
        "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
      };
      path: {
        project: components["parameters"]["ProjectPath"];
        candidate_id: components["parameters"]["CandidateIdPath"];
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ReviewDecisionRequest"];
      };
    };
    responses: {
      /** @description Decision recorded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MergeCandidateResponse"];
        };
      };
      409: components["responses"]["Conflict"];
      default: components["responses"]["Error"];
    };
  };
  deferMergeCandidate: {
    parameters: {
      query?: never;
      header?: {
        /**
         * @description Client-generated key (≤255 chars). Same key + same request hash replays the
         *     stored original response; same key + different request hash → `409
         *     IDEMPOTENCY_CONFLICT`. Keys expire after the configured TTL (default 24h 🔧).
         */
        "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
      };
      path: {
        project: components["parameters"]["ProjectPath"];
        candidate_id: components["parameters"]["CandidateIdPath"];
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ReviewDecisionRequest"];
      };
    };
    responses: {
      /** @description Decision recorded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MergeCandidateResponse"];
        };
      };
      409: components["responses"]["Conflict"];
      default: components["responses"]["Error"];
    };
  };
  querySemantic: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["QueryRequest"];
      };
    };
    responses: {
      /** @description Retrieval result (active build). */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QueryResponse"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  queryGraph: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["QueryRequest"];
      };
    };
    responses: {
      /** @description Retrieval result (active build). */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QueryResponse"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  querySql: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["QueryRequest"];
      };
    };
    responses: {
      /** @description Retrieval result (active build). */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QueryResponse"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  queryGlobal: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["QueryRequest"];
      };
    };
    responses: {
      /** @description Retrieval result (active build). */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QueryResponse"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  queryHybrid: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["QueryRequest"];
      };
    };
    responses: {
      /** @description Retrieval result (active build). */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "data": {
           *         "mode": "hybrid",
           *         "build_id": "7b6a5c4d-3e2f-4a1b-9c8d-7e6f5a4b3c2d",
           *         "results": [
           *           {
           *             "result_type": "chunk",
           *             "id": "9d8c7b6a-5f4e-4d3c-b2a1-0f9e8d7c6b5a",
           *             "title": "onboarding.md#3",
           *             "text": "New hires get access on day one…",
           *             "score": 0.87,
           *             "confidence": 0.91,
           *             "source_refs": [
           *               {
           *                 "source_type": "chunk",
           *                 "id": "9d8c7b6a-5f4e-4d3c-b2a1-0f9e8d7c6b5a",
           *                 "source_uri": "s3://acme/docs/onboarding.md",
           *                 "metadata": {
           *                   "start_offset": 1204,
           *                   "end_offset": 1490
           *                 }
           *               }
           *             ]
           *           }
           *         ],
           *         "graph_context": {
           *           "nodes": [],
           *           "edges": [],
           *           "paths": []
           *         },
           *         "warnings": [
           *           {
           *             "code": "MODE_SKIPPED",
           *             "message": "sql skipped: router confidence 0.12 below threshold"
           *           }
           *         ],
           *         "debug": {
           *           "stores_used": [
           *             "qdrant",
           *             "neo4j"
           *           ],
           *           "retrieval_plan": [
           *             "semantic",
           *             "graph"
           *           ],
           *           "routing_decision": {
           *             "selected": [
           *               "semantic",
           *               "graph"
           *             ],
           *             "skipped": [
           *               "sql",
           *               "global"
           *             ],
           *             "reason": "entity-centric question",
           *             "confidence": 0.83
           *           },
           *           "latency_ms": 412
           *         }
           *       },
           *       "meta": {
           *         "request_id": "1a2b3c4d-5e6f-4a70-8b91-c2d3e4f5a6b7",
           *         "build_id": "7b6a5c4d-3e2f-4a1b-9c8d-7e6f5a4b3c2d",
           *         "elapsed_ms": 431
           *       }
           *     }
           */
          "application/json": components["schemas"]["QueryResponse"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Health report. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  getMetrics: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Metrics. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MetricsResponse"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  getEval: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project: components["parameters"]["ProjectPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Eval report. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EvalResponse"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
}
